spring.application.name=nasa-telegram-bot

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nasa_telegram_bot}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

telegram.bot.token=${TELEGRAM_TOKEN:}
nasa.api.key=${NASA_API_KEY:DEMO_KEY}